### ISSUE TITLE
Create developer guide

### ISSUE THREAD

**Issue by pmjordan** [tliron/turandot#1]
I am trying to get the hello-world example running on my machine. I notice that there are a number of undeclared dependencies. So far I have created the portable container image but to do so I had to install:

jq
pigz
podman - which does not have packages for some distro and architectures. I modified the code to use docker instead. Hope that will be OK down the line. If so you might consider that in your code.

and of course puccini

The scripts also expect directory /Depot/Temporary to be present. I checked this on a distro which did have podman and confirmed it is not created by that package. 

There is also a permissions issue, at least with my docker workaround, as the image file is saved by root at mod 611 and thus cannot be rewritten by scripts/save-portable-container-image running as another user.

**Comment by tliron** [comment]
Thank you. Definitely there needs to be a developer's guide for Turandot. I will leave this issue open for now.

By the way, Podman exactly avoids these Docker permission issues, as it does not require root.

**Comment by pmjordan** [comment]
OK thanks
A further dependency is reposure.

**Comment by tliron** [comment]
[Here is a link to the guide](https://github.com/tliron/turandot/blob/main/QUICKSTART.md).

**Comment by tliron** [comment]
I'll just point out that I create a MUCH simpler quickstart guide that does not require registries (and it goes together with a simpler Hello World example).

The more advanced quickstart guide (and example) is still there.
