### ISSUE TITLE
server could not find the requested resource

### ISSUE THREAD

**Issue by pmjordan** [tliron/turandot#2]
Having created a hello-world.csar, turandot falied to deploy it to my K8 service: 

command was

`turandot -vv service deploy hello-world --file=dist/hello-world.csar`

error response was

`the server could not find the requested resource (get registries.reposure.puccini.cloud default)`

I'm not sure if there are any logs or debugs which I can use to find out more about the error.

**Comment by tliron** [comment]
You need to install both the Turandot and Reposure operators first and provide a site name. This will *sometimes* work:
```
turandot operator install --site=central --role=view
```
The cluster "role" is required to provide access to cluster secrets, which are necessary for accessing a built-in registry.

And then create a default registry using reposure, e.g. for Minikube:
```
reposure registry create default --provider=minikube
```

Until I create a proper guide, you can see this [test](https://github.com/tliron/turandot/blob/main/lab/minikube/test) for Minikube. There is another one for OpenShift, too.

**Comment by pmjordan** [comment]
That gets me to the next stage so closing this issue, but it raises other questions which I will send by email.
