### ISSUE TITLE
Telephony Network Service

### ISSUE THREAD

**Issue by philippemerle** [tliron/turandot#7]
I would like to report you the following issues I encountered on the telephony network service example:

* there are several `entry_schema: the_entry_type` occurrences in many files.
   This one-line form is not allowed by TOSCA 1.3 grammar.
   All occurrences should be replaced by `entry_schema: { type: the_entry_type }`.
* In `profiles/kubernetes/1.0/capabilities.yaml`,
  `- valid_values: [ ExternalName, ClusterIP, NodePort, and LoadBalancer ]`
  should be replaced by
  `- valid_values: [ ExternalName, ClusterIP, NodePort, LoadBalancer ]`,
   i.e. `and ` should be removed.
 * In `profiles/kubernetes/1.0/capabilities.yaml`, 
    `metadata` is not an allowed keyname of attribute definitions.
* In both `asterisk-cnf.yaml` and `asterisk-vnf.yaml` `topology_template:substitution_mappings`,
   `connection` is not a capability to map but a requirement to map.
* there is `namespace: cloud.puccini.xxx` in each `profile.yaml` file
    but `cloud.puccini.xxx` seems to not be a URI as expected by the TOSCA 1.3 grammar.
* In `asterisk-cnf.yaml:node_types:Asterisk:requirements:data-plane`
      both `ns:Connection` and `ns:Routing` relationship types can match the requirement.
      Perhaps should add `relationship: ns:Connection` to avoid this ambiguity. 
* In `asterisk-cnf.yaml:topology_template:substitution_mappings`
   and `asterisk-vnf.yaml:topology_template:substitution_mappings`,
   the capability `deployment` is unmapped but its occurrences is `[1, 'UNBOUNDED']`,
   the capability `trunks` is unmapped but its `occurrences` is `[1, 'UNBOUNDED']`
   and the requirement `trunk` is unmapped but its `occurrences` is `[1, 1]`.
* In `profiles/network-service/profile.yaml`
   `Connection` is an empty relationship type definition.
   Is `valid_target_types: [ Connectable ]` missed?
* Is `node_types:Asterisk:capabilities:connection` useful in both `asterisk-cnf.yaml` and `asterisk-vnf.yaml`?

I hope these could help to improve this example.

**Comment by tliron** [comment]
Thanks for taking a careful look at this! There are a lot of different issues here, some typos, some interpretations of the spec, and some problems with the substitution. Give me some time to process them separately and I'll respond back to you.

I wonder if this would be better as a GitHub "discussion" rather an "issue"? Are you OK with that? If so, you can click the "Convert to discussion" link in the bottom right.

**Comment by philippemerle** [comment]
> Thanks for taking a careful look at this! There are a lot of different issues here, some typos, some interpretations of the spec, and some problems with the substitution. Give me some time to process them separately and I'll respond back to you.

Ok, take your time, I'm not in a hurry .

> I wonder if this would be better as a GitHub "discussion" rather an "issue"? Are you OK with that? If so, you can click the "Convert to discussion" link in the bottom right.

I agree but I don't see any "Convert to discussion" link. Do you?
